import {assign} from '@xstate/immer'
import {useInterpret, useService} from '@xstate/react'
import {isArray, keyBy} from 'lodash-es'
import React from 'react'
import {v4 as uniqueId} from 'uuid'
import {interpret, Interpreter, Machine, TypegenDisabled} from 'xstate'
import cssColorNames from './css-color-names.json'
import exampleScales from './example-scales.json'
import {applyCurve} from './easings'
import {Channel, Color, Curve, Palette, Scale} from './types'
import {clamp, getColorName, getRange, hexToColor, predictColorName, randomIntegerInRange} from './utils'

const GLOBAL_STATE_KEY = 'global_state'

// Re-derives every driven channel from its endpoints. Called after anything
// that touches a scale's colors, so a driven channel can never be left showing
// a shape its preset doesn't produce -- whichever way the colors moved (drag,
// nudge, inspector field, an inserted or deleted color), the answer is the same.
function applyCurves(scale: Scale) {
  const links = Object.entries(scale.curves ?? {}) as [Channel, Curve | undefined][]

  for (const [channel, curve] of links) {
    if (!curve) continue

    const values = applyCurve(
      scale.colors.map(color => color[channel]),
      curve
    )

    scale.colors.forEach((color, index) => {
      color[channel] = values[index]
    })
  }
}

type MachineContext = {
  palettes: Record<string, Palette>
  past: Record<string, Palette>[]
  future: Record<string, Palette>[]
}

type MachineEvent =
  | {
      type: 'CREATE_PALETTE'
      paletteId: string
      name?: string
      // Scales to seed the palette with, as name -> hex(es) light->dark (the
      // shape of example-scales.json and the template files). Omitted falls back
      // to the built-in example scales; an empty object makes a blank palette.
      scales?: Record<string, string[] | string>
    }
  | {
      type: 'DELETE_PALETTE'
      paletteId: string
    }
  | {
      type: 'CHANGE_PALETTE_NAME'
      paletteId: string
      name: string
    }
  | {
      type: 'IMPORT_SCALES'
      paletteId: string
      scales: Record<string, Scale>
      replace: boolean
    }
  | {
      type: 'CHANGE_PALETTE_BACKGROUND_COLOR'
      paletteId: string
      backgroundColor: string
    }
  | {
      type: 'CREATE_SCALE'
      paletteId: string
    }
  | {
      type: 'DELETE_SCALE'
      paletteId: string
      scaleId: string
    }
  | {
      type: 'CHANGE_SCALE_NAME'
      paletteId: string
      scaleId: string
      name: string
    }
  | {
      type: 'INSERT_COLOR'
      paletteId: string
      scaleId: string
      index: number
    }
  | {
      type: 'DELETE_COLOR'
      paletteId: string
      scaleId: string
      index: number
    }
  | {
      type: 'CHANGE_COLOR_VALUE'
      paletteId: string
      scaleId: string
      index: number
      value: Partial<Color>
    }
  | {
      type: 'CHANGE_COLOR_NAME'
      paletteId: string
      scaleId: string
      index: number
      name: string
    }
  | {
      type: 'TOGGLE_COLOR_LOCK'
      paletteId: string
      scaleId: string
      index: number
    }
  | {
      type: 'CHANGE_SCALE_COLORS'
      paletteId: string
      scaleId: string
      colors: Color[]
    }
  | {
      type: 'CHANGE_SCALE_CURVE'
      paletteId: string
      scaleId: string
      channel: Channel
      // null detaches the curve, leaving the colors wherever it last put them.
      curve: Curve | null
    }
  | {type: 'UNDO'}
  | {type: 'REDO'}

const machine = Machine<MachineContext, MachineEvent>({
  id: 'global-state',
  context: {
    palettes: {},
    past: [],
    future: []
  },
  initial: 'idle',
  on: {
    UNDO: {
      actions: assign(context => {
        if (context.past.length > 0) {
          // Insert the present state at the beginning of the future
          context.future.push(context.palettes)
          // Set the present to the last state in the past
          context.palettes = context.past[context.past.length - 1]
          // Remove the last state from the past
          context.past = context.past.slice(0, context.past.length - 1)
        }
      })
    },
    REDO: {
      actions: assign(context => {
        if (context.future.length > 0) {
          // Insert the present state at the beginning of the past
          context.past.push(context.palettes)
          // Set the present to the last state in the future
          context.palettes = context.future[0]
          // Remove the first state from the future
          context.future = context.future.slice(1)
        }
      })
    },
    CREATE_PALETTE: {
      // The paletteId is generated by the caller so it can navigate to the new
      // palette after dispatching (navigation lives in the component, not here).
      actions: assign((context, event) => {
        const paletteId = event.paletteId
        // A defined-but-empty `scales` means the caller chose a blank palette,
        // so it must win over the example fallback -- only an absent field falls
        // back to the built-in examples.
        const source = event.scales ?? exampleScales
        const scales: Scale[] = Object.entries(source).map(([name, scale]) => {
          const id = uniqueId()
          const scaleArray = isArray(scale) ? scale : [scale]
          return {
            id,
            name,
            colors: scaleArray.map((hex, index) => ({...hexToColor(hex), name: getColorName([], index)}))
          }
        })
        context.palettes[paletteId] = {
          id: paletteId,
          // The name comes from the create dialog; an untouched field still has
          // to produce a palette, so the placeholder it showed is the fallback.
          name: event.name?.trim() || 'Untitled',
          backgroundColor: '#ffffff',
          scales: keyBy(scales, 'id')
        }
      })
    },
    DELETE_PALETTE: {
      target: 'debouncing',
      actions: assign((context, event) => {
        delete context.palettes[event.paletteId]
      })
    },
    CHANGE_PALETTE_NAME: {
      target: 'debouncing',
      actions: assign((context, event) => {
        context.palettes[event.paletteId].name = event.name
      })
    },
    CHANGE_PALETTE_BACKGROUND_COLOR: {
      target: 'debouncing',
      actions: assign((context, event) => {
        context.palettes[event.paletteId].backgroundColor = event.backgroundColor
      })
    },
    IMPORT_SCALES: {
      target: 'debouncing',
      actions: assign((context, event) => {
        if (event.replace) {
          context.palettes[event.paletteId].scales = event.scales
        } else {
          Object.assign(context.palettes[event.paletteId].scales, event.scales)
        }
      })
    },
    CREATE_SCALE: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scaleId = uniqueId()
        const randomIndex = randomIntegerInRange(0, cssColorNames.length)
        const name = cssColorNames[randomIndex]
        const color = {...hexToColor(name), name: getColorName([], 0)}

        context.palettes[event.paletteId].scales[scaleId] = {
          id: scaleId,
          name,
          colors: [color]
        }
      })
    },
    DELETE_SCALE: {
      target: 'debouncing',
      actions: assign((context, event) => {
        delete context.palettes[event.paletteId].scales[event.scaleId]
      })
    },
    CHANGE_SCALE_NAME: {
      target: 'debouncing',
      actions: assign((context, event) => {
        context.palettes[event.paletteId].scales[event.scaleId].name = event.name
      })
    },
    INSERT_COLOR: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scale = context.palettes[event.paletteId].scales[event.scaleId]
        const colors = scale.colors
        const n = colors.length

        if (n === 0) return

        // Where the new value lands in a channel: the midpoint of the two
        // neighbours when inserting between swatches, or the trend extrapolated
        // one step past the edge when inserting at the start/end.
        const sample = (values: number[], at: number): number => {
          const len = values.length
          if (at > 0 && at < len) {
            return (values[at - 1] + values[at]) / 2
          }
          if (at <= 0) {
            return len >= 2 ? 2 * values[0] - values[1] : values[0]
          }
          const last = len - 1
          return len >= 2 ? 2 * values[last] - values[last - 1] : values[last]
        }

        const at = clamp(event.index, 0, n)
        // Predict the inserted color's name from the current names before splicing.
        const predictedName = predictColorName(
          colors.map((_, index) => getColorName(colors, index)),
          at
        )
        const newColor: Color = {hue: 0, saturation: 0, lightness: 0, name: predictedName}

        for (const channel of ['hue', 'saturation', 'lightness'] as const) {
          const {min, max} = getRange(channel)

          // The new color follows the ramp of its neighbours.
          newColor[channel] = clamp(
            sample(
              colors.map(color => color[channel]),
              at
            ),
            min,
            max
          )
        }

        colors.splice(at, 0, newColor)
        // The inserted color shifts every later index, so a driven channel's
        // whole ramp is re-sampled -- including when the insert lands on an end
        // and hands the curve a new handle.
        applyCurves(scale)
      })
    },
    DELETE_COLOR: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scale = context.palettes[event.paletteId].scales[event.scaleId]

        if (scale.colors.length > 1) {
          scale.colors.splice(event.index, 1)
          applyCurves(scale)
        }
      })
    },
    CHANGE_COLOR_VALUE: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scale = context.palettes[event.paletteId].scales[event.scaleId]
        Object.assign(scale.colors[event.index], event.value)
        applyCurves(scale)
      })
    },
    CHANGE_COLOR_NAME: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const color = context.palettes[event.paletteId].scales[event.scaleId].colors[event.index]
        if (color) color.name = event.name
      })
    },
    TOGGLE_COLOR_LOCK: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const color = context.palettes[event.paletteId].scales[event.scaleId].colors[event.index]
        if (color) color.locked = !color.locked
      })
    },
    CHANGE_SCALE_COLORS: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scale = context.palettes[event.paletteId].scales[event.scaleId]
        scale.colors = event.colors
        applyCurves(scale)
      })
    },
    CHANGE_SCALE_CURVE: {
      target: 'debouncing',
      actions: assign((context, event) => {
        const scale = context.palettes[event.paletteId].scales[event.scaleId]

        if (event.curve) {
          scale.curves = {...scale.curves, [event.channel]: event.curve}
          // Attaching redraws the channel immediately, so the select's effect is
          // visible without waiting for an endpoint to move -- and so does every
          // nudge of a custom control point. This overwrites whatever the middle
          // colors held; undo is the way back.
          applyCurves(scale)
        } else if (scale.curves) {
          // Detaching leaves the colors exactly where the curve put them and
          // just hands the middle points back.
          delete scale.curves[event.channel]
        }
      })
    }
  },
  states: {
    idle: {
      exit: assign((context, event) => {
        // Insert present state at the end of the past
        context.past.push(context.palettes)

        // Limit length of past
        const size = 50
        context.past = context.past.slice(-size)

        // Clear the future
        context.future = []
      })
    },
    debouncing: {
      after: {
        200: {
          target: 'idle'
        }
      }
    }
  }
})

// @xstate/react's useInterpret returns the raw (TypegenDisabled) Interpreter type,
// while xstate's own `interpret` now wraps it in ResolveTypegenMeta. Pin the context
// to the @xstate/react flavor so the provider value and consumers line up, and cast
// only the fallback default value across the version skew.
type GlobalService = Interpreter<MachineContext, any, MachineEvent, any, TypegenDisabled>
const GlobalStateContext = React.createContext<GlobalService>(interpret(machine) as unknown as GlobalService)

export function GlobalStateProvider({children}: React.PropsWithChildren<{}>) {
  const initialState = React.useMemo(() => getPersistedState() ?? machine.initialState, [])

  const service = useInterpret(machine, {state: initialState, devTools: true}, state => {
    localStorage.setItem(GLOBAL_STATE_KEY, JSON.stringify(state))
  })

  return <GlobalStateContext.Provider value={service}>{children}</GlobalStateContext.Provider>
}

export function useGlobalState() {
  return useService(React.useContext(GlobalStateContext))
}

// The persisted shape from before linked curves were removed: a palette held
// shared curves, a scale pointed a channel at one by id, and the scale's own
// color values were offsets added on top of it.
type LegacyScale = Omit<Scale, 'curves'> & {curves?: Partial<Record<Channel, string>>}
type LegacyPalette = Omit<Palette, 'scales'> & {
  scales: Record<string, LegacyScale>
  curves?: Record<string, {values: number[]}>
}

// Folds each linked curve back into the colors it drove, which is the same sum
// the app used to render, so a migrated palette looks exactly as it did. Without
// this a linked scale would come back as its bare offsets — a lightness of 0
// reading as black. Deletable once no one's localStorage predates the removal.
function foldLegacyCurvesIntoColors(palettes: Record<string, LegacyPalette>) {
  for (const palette of Object.values(palettes)) {
    // `scale.curves` has since been reused for bezier presets, so the palette's
    // own `curves` is what says this is legacy data. Without this guard the
    // migration would strip every preset on load, every load.
    if (!palette.curves) continue

    for (const scale of Object.values(palette.scales)) {
      const links = Object.entries(scale.curves ?? {}) as [Channel, string | undefined][]

      for (const [channel, curveId] of links) {
        const values = curveId ? palette.curves?.[curveId]?.values : undefined
        if (!values) continue

        scale.colors = scale.colors.map((color, index) => ({
          ...color,
          [channel]: color[channel] + (values[index] ?? 0)
        }))
      }

      delete scale.curves
    }

    delete palette.curves
  }
}

function getPersistedState(): typeof machine.initialState | null {
  try {
    const state = JSON.parse(localStorage.getItem(GLOBAL_STATE_KEY) ?? '')
    const {palettes, past = [], future = []} = state?.context ?? {}

    // The undo stacks hold whole palette snapshots, so they need folding too —
    // otherwise stepping back lands on a palette the app can no longer read.
    for (const snapshot of [palettes, ...past, ...future]) {
      if (snapshot) foldLegacyCurvesIntoColors(snapshot)
    }

    return state
  } catch (e) {
    return null
  }
}
